jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: 'python -m pip install --upgrade pip

        pip install wheel

        pip install -r requirements.txt

        '
    - name: build Anki Deck most-common-spanish-words-v5.txt
      run: "\npython main.py lists/es/most-common-spanish-words-v5.txt es en 15000\n\
        \n                    git config --local user.email \"41898282+github-actions[bot]@users.noreply.github.com\"\
        \n\n                    git config --local user.name \"github-actions[bot]\"\
        \n\n                    git add CreatedDecks\ngit rm .github/workflows/lists.es.most-common-spanish-words-v5.txt.yml\n\
        git commit -m \"Uploaded Deck lists.es.most-common-spanish-words-v5.txt\"\
        \ -a\n                   \ngit pull -r\n           "
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: ${{ github.ref }}
        github_token: ${{ secrets.ADD_NEW }}
name: '"lists/es/most-common-spanish-words-v5.txt" - GW'
'on':
  push:
    branches:
    - master
