
name: magnet

on:
  workflow_dispatch:
    inputs:
      magnet:
        description: 'Magnet'
        required: true
        type: string

permissions:
  contents: read

jobs:
  build:
    runs-on: linux-latest
    strategy:
      matrix:
        node-version: [16.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: ins
        run: npm install webtorrent-cli -g
      - name: download
        run: webtorrent "${{ github.event.inputs.magnet }}"
      - name: Upload
        uses: Difegue/action-megacmd@master
        with:
          args: put . .
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
