
name: slow magnet

on:
  workflow_dispatch:
    inputs:
      magnet:
        description: 'slow Magnet'
        required: true
        type: string

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [16.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          pip install -r requirements.txt
      - name: ins
        run: npm install git+https://github.com/Persie0/webtorrent-cli-timelimit -g
      - name: download
        run: webtorrent "${{ github.event.inputs.magnet }}"
      - name: Upload
        uses: Difegue/action-megacmd@master
        with:
          args: put . .
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .github/workflows/slow_magnet_progress.yml
          git commit -m "Downloading" -a
          git pull -r
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.ADD_NEW }}
          branch: ${{ github.ref }}
