# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Create Decks from directory

on:
  workflow_dispatch:
    inputs:
      directory:
        description: 'Which directory should be used e.g.: lists/es/'
        required: true
        type: string
      from:
        description: 'Language of words from given .txt files '
        required: true
        type: string
      to:
        description: 'Language to which should be translated to in short form (see Readme)'
        required: true
        type: string

      numberOfWords:
        description: 'How many Cards/Words your Anki Deck should have (Whole Number!) 
        Write 0 to go through the whole .txt file.
        There is a 6h Github Action time limit!!! 
        So max. Word (in Github Actions) are ca. 25000'
        required: true
        type: string


permissions:
  contents: write
  pull-requests: write
  actions: write


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
        fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install -r requirements.txt
    - name: create workflow file
      run: |
        python generate_workflows.py ${{ github.event.inputs.directory }} ${{ github.event.inputs.from }} ${{ github.event.inputs.to }} ${{ github.event.inputs.numberOfWords }}
    - name: Commit files
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add .github/workflows
        git commit -m "Creating Decks from Directory" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.ADD_NEW }}
        branch: ${{ github.ref }}

